env:
  browser: true
  es2021: true
extends:
  - google
parser: '@typescript-eslint/parser'
ignorePatterns:
  - "lib/"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {}
