id: 'talk-on-paper'
title: 'Talk on Paper'
imageSrc: 'https://via.placeholder.com/150?Text=Talk%20on%20Paper'
author: 
  - name: 'leeyee11'
    profileImageSrc: 'https//via.placeholder.com/150?Text=LeeYee11'
    